services:
  node-app:
    build: .
    container_name: eco-app
    command: pnpm start
    ports:
      - "${NODE_PORT}:3000"
    env_file:
      - .env          # development
      # - .env.test   # uncomment when running tests
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mssql
      - minio
      - redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./db-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # API endpoint
      - "9001:9001"   # Admin UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  mssql_data:
  minio_data:
  redis_data:
