services:
  node-app:
    build: .
    container_name: eco-app
    command: pnpm start
    ports:
      - "${NODE_PORT}:3000"
    env_file:
      - .env          # development
      # - .env.test   # uncomment when running tests
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./db-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  mssql_data:
